apps/negocio/urls.py
from django.conf.urls import  include, url
from rest_framework.routers import DefaultRouter
from .views import CrearNegocio, ListaNegocio, DetailNegocio, DeleteNegocio
from .viewsets import NegocioViewSet

router = DefaultRouter()
router.register(r'api', NegocioViewSet)

urlpatterns = [
    url(r'^$', ListaNegocio.as_view(), name="lista_negocio"),
    url(r'^crear$', CrearNegocio.as_view(), name="crear_negocio"),
    url(r'^buscar$', DetailNegocio.as_view(), name="detail_negocio"),
    url(r'^eliminar$', DeleteNegocio.as_view(), name="eliminar_negocio"),
    url(r'^', include(router.urls)),
]

webretail/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^negocio/', include('apps.negocio.urls', namespace='negocio')),
    url(r'^fidelizacion/', include('apps.fidelizacion.urls')),
    url(r'^local/', include('apps.local.urls',)),
    url(r'^categoria/', include('apps.categoria.urls')),
    url(r'^coleccion/', include('apps.coleccion.urls')),
    url(r'^banner/', include('apps.banner.urls')),
    url(r'^productos/', include('apps.productos.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

apps/negocio/models.py
from django.db import models
from ..tipo_negocio.models import TipoNegocio
import os


class Negocio(models.Model):
    """
    Description: Model Description
    """
    tipo_negocio = models.ForeignKey(TipoNegocio, on_delete=models.CASCADE, related_name='tiponegocio_tienda',)
    nombre = models.CharField(max_length=100, )
    pagina_facebook = models.CharField(max_length=200, )
    status = models.BooleanField(null=False,default=True)
    logo = models.ImageField(upload_to='logos')
    logo_ba = models.TextField(null=True, blank=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.nombre

apps/negocio/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from .models import Negocio
import json
from django.http import HttpResponse
from django.conf import settings
import base64
from PIL import Image
import os
from django.db.models import Count, F


class ListaNegocio(ListView):

    template_name = 'negocio/listar.html'
    model = Negocio
    titulo = 'Listar Negocios'

    def get_context_data(self, **kwargs):
        context = super(ListaNegocio, self).get_context_data(**kwargs)
        queryset_negocios = self.model.objects.all()
        queryset_negocios = queryset_negocios.annotate(num_local=Count('negocio_local'), negocio_id=F('negocio_fidelizacion'))
        context["negocios"] = queryset_negocios.values('id', 'nombre', 'logo', 'num_local', 'negocio_id',)
        context['titulo'] = self.titulo
        return context


class DetailNegocio(DetailView):
    model = Negocio

    def get(self, request, *args, **kwargs):
        ids = self.request.GET.get('id')
        queryset = self.model.objects.all()
        queryset= queryset.filter(id=ids)
        queryset= queryset.values('nombre', 'status', 'logo')
        data = {}
        for value in queryset:
            data = value
        return HttpResponse(json.dumps(data), status=200, content_type='application/json')



class CrearNegocio(CreateView):
    template_name = 'negocio/form.html'
    model = Negocio
    fields = ['id', 'tipo_negocio', 'nombre', 'pagina_facebook', 'status', 'logo',]
    titulo = 'Crear Negocio'

    def get_context_data(self, **kwargs):
        context = super(CrearNegocio, self).get_context_data(**kwargs)
        context['titulo'] = self.titulo
        context["negocios"] = self.model.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        add = form.save(commit=False)
        response_data = {}

        if form.is_valid():
            nombre = request.FILES['logo'].name
            ruta_image = settings.MEDIA_ROOT
            archivo = ruta_image+'/logos/'+str(nombre)
            img = Image.open(request.FILES['logo'])
            img.thumbnail((480, 480), Image.ANTIALIAS)
            img.save(archivo)

            image = open(archivo)
            fot_c =  image.read()
            logo_ba = base64.encodestring(fot_c)
            add.logo_ba = logo_ba
            os.remove(archivo)
            valor = add.save()
            # Fin Guardar base64
            response_data['success'] = 'error'
            if valor != 'error':
                response_data['success'] = 'ok'

            return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')


class DeleteNegocio(DeleteView):
    model = Negocio

    def delete(self, request, *args, **kwargs):

        ids = request.POST.get('id')
        negocio_obj = self.model.objects.get(id=ids)
        negocio_obj.delete()
        response_data = {}
        response_data['eliminar'] = 'ok'
        return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')

templates/negocio/form.html
<!DOCTYPE html>
<html>
<head>

    <title>{{titulo}}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/estilo.css" />
    <script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.js"></script>
</head>
<body>

    <h1>{{titulo}}</h1>

    <form action="{% url 'negocio:crear_negocio'%}" method="post" id="formulario">
        {% csrf_token %}
        {{form.as_p}}
        <button type="button" id="crear">Crear</button>
    </form>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#crear').click(function(e){
                var $frmcategories = $('#formulario')
                var $url = $frmcategories.attr('action');

                var data_send = new FormData($frmcategories[0]);
                $.ajax({
                    url: $url,
                    type: "POST",
                    dataType: "json",
                    data: data_send,
                    cache: false,
                    contentType: false,
                    processData: false
                }).done(function( data ) {
                    if ( data.success == 'ok' ) {
                        window.location = '/negocio'
                    }
                })
            });

            // $("#id_logo").on('change',function(){
            //     var selectedFile = this.files[0];
            //     selectedFile.convertToBase64(function(base64){
            //         alert(base64);
            //     })
            // });
        });

        File.prototype.convertToBase64 = function(callback){
            var reader = new FileReader();
            reader.onload = function(e) {
                callback(e.target.result)
            };
            reader.onerror = function(e) {
                callback(null);
            };
            reader.readAsDataURL(this);
        };

    </script>
</body>
</html>

templates/negocio/listar.html
<!DOCTYPE html>
<html>
<head>
    <title>{{titulo}}</title>

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/estilo.css" />
    <script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.js"></script>
</head>
<body>
    <h1>{{titulo}}</h1>
    <a href="{% url 'negocio:crear_negocio'%}">Registrar</a>
    <table border='1' id="tabla">
        <thead>
            <tr>
                <td>&nbsp;</td>
                <td>Negocio</td>
                <td>Modificar</td>
                <td>Eliminar</td>
                <td>Locales</td>
                <td>Fidelizacion</td>
                <!-- <td>&nbsp;</td> -->
            </tr>
        </thead>
        <tbody>
            {% for lista in negocios %}
            <tr>
                <td>
                    <img style="width: 48px;height: 48px;" src="{{ MEDIA_URL }}{{lista.logo}}" alt="Logo" />
                </td>
                <td>
                    {{lista.nombre}}
                </td>
                <td>
                    <a data-id="{{lista.id}}" class="modificar" href="{% url "negocio:detail_negocio"%}?id={{lista.id}}">Modificar</a>
                </td>
                <td>
                    <a data-id="{{lista.id}}" class="eliminar" href="{% url "negocio:eliminar_negocio"%}">Eliminar</a>
                </td>
                <td>
                    <a href="{% url "lista_local" lista.id%}">{{lista.num_local}}</a>
                </td>
                <td>
                    {% if lista.negocio_id is None %}
                        <a href="{% url "crear_fidelizacion" lista.id%}">Crear</a>
                    {% else%}
                        <a href="{% url "lista_fidelizacion" lista.id%}">Ver</a>
                    {% endif%}
                </td>
                <!-- <td>
                    <img src="data:image/png;base64,{{ lista.logo_ba }}" alt="">
                </td> -->
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla tbody tr td').on('click','a.modificar', buscar )
            $('#tabla tbody tr td').on('click','a.eliminar', eliminar )
        });
        var buscar = function(event) {
            event.preventDefault();
            var $url = $(this).attr('href')
            $.get($url, function(data) {
                console.log(data.descripcion)
            },'json');
        };

        var eliminar = function(event) {
            event.preventDefault();
            var $url = $(this).attr('href')
            var $id  = $(this).data('id');
            var token = $('input[name="csrfmiddlewaretoken"]').val();
            $.post($url,{id:$id,csrfmiddlewaretoken:token}, function(data) {
                console.log(data.descripcion)
            },'json');
        };
    </script>
</body>
</html>