apps/fidelizacion/urls.py
from django.conf.urls import  include, url
from rest_framework.routers import DefaultRouter
from .views import CrearFidelizacion, ListaFidelizacion, DetailFidelizacion, DeleteFidelizacion
# from .viewsets import LocalViewSet

# router = DefaultRouter()
# router.register(r'api', LocalViewSet)

urlpatterns = [
    url(r'^fidelizacion/(?P<pk>\d+)/$', ListaFidelizacion.as_view(), name="lista_fidelizacion"),
    url(r'^crear/(?P<pk>\d+)/$', CrearFidelizacion.as_view(), name="crear_fidelizacion"),
    url(r'^buscar/$', DetailFidelizacion.as_view(), name="detail_fidelizacion"),
    url(r'^eliminar$', DeleteFidelizacion.as_view(), name="eliminar_fidelizacion"),
    # url(r'^', include(router.urls)),
]

webretail/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^negocio/', include('apps.negocio.urls', namespace='negocio')),
    url(r'^fidelizacion/', include('apps.fidelizacion.urls')),
    url(r'^local/', include('apps.local.urls',)),
    url(r'^categoria/', include('apps.categoria.urls')),
    url(r'^coleccion/', include('apps.coleccion.urls')),
    url(r'^banner/', include('apps.banner.urls')),
    url(r'^productos/', include('apps.productos.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

apps/fidelizacion/models.py
from django.db import models

from ..negocio.models import Negocio

class Fidelizacion(models.Model):
    """
    Description: Model Description
    """
    moneda = models.FloatField(null=True, blank=True)
    puntos = models.IntegerField()
    descuento = models.FloatField()
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, related_name='negocio_fidelizacion', null=True)
    date_create = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.moneda

apps/negocio/models.py
from django.db import models
from ..tipo_negocio.models import TipoNegocio
import os


class Negocio(models.Model):
    """
    Description: Model Description
    """
    tipo_negocio = models.ForeignKey(TipoNegocio, on_delete=models.CASCADE, related_name='tiponegocio_tienda',)
    nombre = models.CharField(max_length=100, )
    pagina_facebook = models.CharField(max_length=200, )
    status = models.BooleanField(null=False,default=True)
    logo = models.ImageField(upload_to='logos')
    logo_ba = models.TextField(null=True, blank=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.nombre

apps/fidelizacion/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from .models import Fidelizacion
import json
from django.http import HttpResponse
from django.conf import settings
import base64
from PIL import Image
import os
from django.db.models import F
from django.db.models import  F


class ListaFidelizacion(ListView):

    template_name = 'fidelizacion/listar.html'
    model = Fidelizacion
    titulo = 'Listar Fidelizaciones'

    def get_context_data(self, **kwargs):
        negocio_id = self.kwargs['pk']
        context = super(ListaFidelizacion, self).get_context_data(**kwargs)
        queryset_fidelizaciones = self.model.objects.all()
        queryset_fidelizaciones =  queryset_fidelizaciones.filter(negocio = negocio_id)
        queryset_fidelizaciones = queryset_fidelizaciones.annotate( nombre_negocio=F('negocio__nombre'))
        queryset_fidelizaciones = queryset_fidelizaciones.values('id', 'moneda', 'puntos', 'nombre_negocio' )
        context["fidelizaciones"] = queryset_fidelizaciones
        context['titulo'] = self.titulo
        context['negocio_id'] = negocio_id
        return context


class DetailFidelizacion(DetailView):
    model = Fidelizacion

    def get(self, request, *args, **kwargs):
        ids = self.request.GET.get('id')
        queryset = self.model.objects.all()
        queryset= queryset.filter(id=ids)
        queryset= queryset.values('id', 'moneda', 'puntos', 'descuento')
        data = {}
        for value in queryset:
            data = value
        return HttpResponse(json.dumps(data), status=200, content_type='application/json')



class CrearFidelizacion(CreateView):
    template_name = 'fidelizacion/form.html'
    model = Fidelizacion
    fields = ['id', 'moneda', 'puntos', 'negocio' ,'descuento']
    titulo = 'Crear Fidelizacion'

    def get_context_data(self, **kwargs):
        negocio_id = self.kwargs['pk']
        context = super(CrearFidelizacion, self).get_context_data(**kwargs)
        context['titulo'] = self.titulo
        context["fidelizaciones"] = self.model.objects.all()
        context['negocio_id'] = negocio_id
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        add = form.save(commit=False)
        response_data = {}
        if form.is_valid():
            valor = add.save()
            response_data['success'] = 'error'
            if valor != 'error':
                response_data['success'] = 'ok'
            return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')


class DeleteFidelizacion(DeleteView):
    model = Fidelizacion

    def delete(self, request, *args, **kwargs):

        ids = request.POST.get('id')
        Fidelizacion_obj = self.model.objects.get(id=ids)
        Fidelizacion_obj.delete()
        response_data = {}
        response_data['eliminar'] = 'ok'
        return HttpResponse(json.dumps(response_data), status=200, content_type='application/json')

templates/fidelizacion/form.html
<!DOCTYPE html>
<html>
<head>

    <title>{{titulo}}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/estilo.css" />
    <script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.js"></script>
</head>
<body>

    <h1>{{titulo}}</h1>
    <form action="{% url 'crear_fidelizacion' negocio_id%}" method="post" id="formulario">
        {% csrf_token %}
        <p>
            <label for="id_moneda">Moneda:</label>
            <input id="id_moneda" name="moneda" step="any" type="text" />
        </p>
        <p>
            <label for="id_puntos">Puntos:</label>
            <input id="id_puntos" name="puntos" type="text" required />
        </p>
        <p>
        <label for="id_descuento">Descuento:</label>
        <input id="id_descuento" name="descuento" type="text" />
        </p>
        <input type="hidden" id="negocio" name="negocio" value="{{negocio_id}}" placeholder="">
        <button type="button" id="crear">Crear</button>
    </form>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#crear').click(function(e){
                var $frmcategories = $('#formulario')
                var $url = $frmcategories.attr('action');

                var data_send = new FormData($frmcategories[0]);
                var $negocio = $('#negocio').val();
                $.ajax({
                    url: $url,
                    type: "POST",
                    dataType: "json",
                    data: data_send,
                    cache: false,
                    contentType: false,
                    processData: false
                }).done(function( data ) {
                    if ( data.success == 'ok' ) {
                        window.location = '/negocio'
                    }
                })
            });

            // $("#id_logo").on('change',function(){
            //     var selectedFile = this.files[0];
            //     selectedFile.convertToBase64(function(base64){
            //         alert(base64);
            //     })
            // });
        });

        File.prototype.convertToBase64 = function(callback){
            var reader = new FileReader();
            reader.onload = function(e) {
                callback(e.target.result)
            };
            reader.onerror = function(e) {
                callback(null);
            };
            reader.readAsDataURL(this);
        };

    </script>
</body>
</html>

templates/fidelizacion/listar.html
<!DOCTYPE html>
<html>
<head>
    <title>{{titulo}}</title>

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/estilo.css" />
    <script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.js"></script>
</head>
<body>
    <h1>{{titulo}}</h1>
    <a href="{% url 'crear_fidelizacion' negocio_id%}">Registrar</a>
    <table border='1' id="tabla">
        <thead>
            <tr>
                <td>Local</td>
                <td>Soles</td>
                <td>Puntos</td>
                <td>Modificar</td>
                <td>Eliminar</td>
                <!-- <td>&nbsp;</td> -->
            </tr>
        </thead>
        <tbody>
            {% for lista in fidelizaciones %}
            <tr>
                <td>
                {{lista.nombre_negocio}}
                </td>
                <td>
                    {{lista.moneda}}
                </td>
                <td>
                    {{lista.puntos}}
                </td>
                <td>
                    <a data-id="{{lista.id}}" class="modificar" href="{% url "detail_fidelizacion"%}?id={{lista.id}}">Modificar</a>
                </td>
                <td>
                    <a data-id="{{lista.id}}" class="eliminar" href="{% url "eliminar_fidelizacion"%}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla tbody tr td').on('click','a.modificar', buscar )
            $('#tabla tbody tr td').on('click','a.eliminar', eliminar )
        });
        var buscar = function(event) {
            event.preventDefault();
            var $url = $(this).attr('href')
            $.get($url, function(data) {
                console.log(data.descripcion)
            },'json');
        };

        var eliminar = function(event) {
            event.preventDefault();
            var $url = $(this).attr('href')
            var $id  = $(this).data('id');
            var token = $('input[name="csrfmiddlewaretoken"]').val();
            $.post($url,{id:$id,csrfmiddlewaretoken:token}, function(data) {
                console.log(data.descripcion)
            },'json');
        };
    </script>
</body>
</html>